import fs from 'node:fs';
import path from 'node:path';
import { spawn, spawnSync } from 'node:child_process';

const IGNORE_DIRS=new Set(['.git','node_modules','dist','build','.astro','.svelte-kit','.next','.nuxt','coverage','.venv','venv','__pycache__']);
const WATCH_EXTS=new Set(['.astro','.tsx','.ts','.jsx','.js','.vue','.svelte','.html','.htm','.css','.scss','.sass','.less','.py','.c','.h','.cpp','.hpp']);
const safeRel=v=>String(v||'').replace(/\\+/g,'/').replace(/^\.\//,'').replace(/\/{2,}/g,'/');
function safeJoin(root,rel){const base=path.resolve(root),target=path.resolve(base,safeRel(rel));if(target!==base&&!target.startsWith(base+path.sep))throw new Error('Path escapes workspace root');return target;}
function fingerprint(content=''){let h=0x811c9dc5;for(let i=0;i<String(content).length;i++){h^=String(content).charCodeAt(i);h=Math.imul(h,0x01000193)>>>0;}return h.toString(16).padStart(8,'0');}
function literalAttr(v){if(v==null)return null;if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return v;if(Array.isArray(v)){const text=v.map(x=>literalAttr(x)).filter(x=>typeof x==='string').join('');return text||null;}if(typeof v==='object'){if(typeof v.value==='string')return v.value;if(typeof v.data==='string')return v.data;if(typeof v.raw==='string')return v.raw;}return null;}
function styleObjectFromString(value=''){const out={};for(const p of String(value).split(';')){const i=p.indexOf(':');if(i<0)continue;const k=p.slice(0,i).trim().replace(/-([a-z])/g,(_,c)=>c.toUpperCase()),v=p.slice(i+1).trim();if(k&&v)out[k]=v;}return out;}
function selectorFor(attrs={}){const cls=attrs.class||attrs.className;if(typeof cls==='string'&&cls.trim())return `.${cls.trim().split(/\s+/)[0]}`;if(typeof attrs.id==='string')return `#${attrs.id}`;return null;}
function compactNode({kind='element',tag='',attributes={},text=null,style={},start=null,end=null,line=null,column=null,symbolPath=null,parser='',confidence=.9}={}){return {kind,tag,attributes,text,style,start,end,line,column,dataUiId:typeof attributes['data-ui-id']==='string'?attributes['data-ui-id']:null,selectorPath:selectorFor(attributes),symbolPath,parser,confidence};}

function fallbackMarkup(source,parser='portable-markup'){
  const nodes=[];const re=/<([A-Za-z][\w:.-]*)([^>]*?)>/g;let m;while((m=re.exec(source))){if(m[0].startsWith('</'))continue;const attrs={},ar=/([:@A-Za-z_][\w:.-]*)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|\{([^}]*)\}|([^\s>]+)))?/g;let a;while((a=ar.exec(m[2]))){if(!a[1])continue;attrs[a[1]]=a[2]??a[3]??(a[4]!=null?{expression:a[4].trim()}:a[5]??true);}const close=new RegExp(`</${m[1]}\\s*>`,'g');close.lastIndex=re.lastIndex;const cm=close.exec(source),inner=cm?source.slice(re.lastIndex,cm.index):'',text=inner&&!/[<>]/.test(inner)?inner.trim():null;nodes.push(compactNode({tag:m[1],attributes:attrs,text,style:styleObjectFromString(typeof attrs.style==='string'?attrs.style:''),start:m.index,end:cm?close.lastIndex:re.lastIndex,parser,confidence:attrs['data-ui-id']?1:.72}));}
  const styleRules=[];const css=/([^{}]+)\{([^{}]*)\}/g;while((m=css.exec(source))){const selector=m[1].trim();if(!selector||selector.startsWith('@')||selector.includes('<'))continue;styleRules.push({selector,style:styleObjectFromString(m[2]),start:m.index,end:css.lastIndex});}
  for(const n of nodes)for(const r of styleRules)if(n.selectorPath&&r.selector.split(',').map(x=>x.trim()).includes(n.selectorPath))Object.assign(n.style,r.style);
  return {parser,nodes,styleRules,diagnostics:[],confidence:nodes.some(n=>n.dataUiId)?.95:.72};
}

function genericWalk(value,fn,seen=new Set()){if(!value||typeof value!=='object'||seen.has(value))return;seen.add(value);fn(value);if(Array.isArray(value)){for(const x of value)genericWalk(x,fn,seen);return}for(const [k,v] of Object.entries(value)){if(['parent','parentNode'].includes(k))continue;genericWalk(v,fn,seen)}}
function astAttrs(raw=[]){const out={};for(const a of raw||[]){const name=a?.name?.name||a?.name||a?.key?.name;if(!name||typeof name!=='string')continue;const value=literalAttr(a?.value??a?.expression??a?.initializer??a?.data);out[name]=value??true;}return out;}
function posOf(node){const start=node?.position?.start?.offset??node?.loc?.start?.offset??node?.start??null,end=node?.position?.end?.offset??node?.loc?.end?.offset??node?.end??null;return {start:Number.isFinite(start)?start:null,end:Number.isFinite(end)?end:null,line:node?.position?.start?.line??node?.loc?.start?.line??null,column:node?.position?.start?.column??node?.loc?.start?.column??null};}

function jsxName(node){if(!node)return '';if(typeof node==='string')return node;if(typeof node.name==='string')return node.name;if(node.type==='JSXIdentifier')return node.name||'';if(node.type==='JSXMemberExpression')return `${jsxName(node.object)}.${jsxName(node.property)}`;return ''}
function estreeJsxAttrs(opening,source){const out={};for(const a of opening?.attributes||[]){if(a?.type!=='JSXAttribute')continue;const name=jsxName(a.name);if(!name)continue;if(!a.value){out[name]=true;continue}if(a.value.type==='Literal'||a.value.type==='StringLiteral'){out[name]=a.value.value;continue}if(a.value.type==='JSXExpressionContainer'){const e=a.value.expression;if(e?.type==='Literal'||e?.type==='StringLiteral'||e?.type==='NumericLiteral'||e?.type==='BooleanLiteral')out[name]=e.value;else out[name]={expression:source.slice(e?.start??a.value.start??0,e?.end??a.value.end??0)};continue}out[name]={expression:source.slice(a.value.start??0,a.value.end??0)}}return out}
function collectAstroNodes(ast,source,parser){const nodes=[];genericWalk(ast,n=>{if(n?.type==='JSXElement'&&n.openingElement){const opening=n.openingElement,tag=jsxName(opening.name),attributes=estreeJsxAttrs(opening,source),children=n.children||[],plain=children.filter(c=>c?.type==='JSXText').map(c=>c.value??c.raw??'').join('').trim();if(tag)nodes.push(compactNode({tag,attributes,text:plain||null,style:styleObjectFromString(typeof attributes.style==='string'?attributes.style:''),start:n.start??opening.start??null,end:n.end??opening.end??null,line:n.loc?.start?.line??null,column:n.loc?.start?.column!=null?n.loc.start.column+1:null,parser,confidence:attributes['data-ui-id']?1:.95}));return}
    if(!Array.isArray(n?.attributes)||!(n.name||n.tagName))return;const tag=typeof n.name==='string'?n.name:typeof n.tagName==='string'?n.tagName:'';if(!tag)return;const attributes=astAttrs(n.attributes),children=Array.isArray(n.children)?n.children:[],texts=children.filter(c=>c?.type==='text'||c?.type==='Text').map(c=>c.value??c.data??'').join('').trim(),p=posOf(n);nodes.push(compactNode({tag,attributes,text:texts||null,style:styleObjectFromString(typeof attributes.style==='string'?attributes.style:''),...p,parser,confidence:attributes['data-ui-id']?1:.92}));});return nodes}
async function inspectAstro(source){
  const errors=[];
  for(const spec of ['@astrojs/compiler-rs','@astrojs/compiler']){
    try{const mod=await import(spec);if(typeof mod.parse!=='function')continue;const result=await mod.parse(source,{position:true});const ast=result?.ast||result;const nodes=collectAstroNodes(ast,source,spec);const fb=fallbackMarkup(source,spec);return {...fb,parser:spec,nodes:nodes.length?nodes:fb.nodes,astValidated:true,diagnostics:(result?.diagnostics||[]).map(d=>d?.text||d?.message||String(d)),confidence:nodes.length?.98:.9};}catch(error){errors.push(`${spec}: ${error.message}`)}
  }
  const fb=fallbackMarkup(source);fb.diagnostics.push(`Astro compiler unavailable or parse failed: ${errors.join(' | ')}`);return fb;
}
async function inspectReact(source,filename){
  try{const ts=await import('typescript');const kind=/\.jsx$/i.test(filename)?ts.ScriptKind.JSX:ts.ScriptKind.TSX,sf=ts.createSourceFile(filename||'Component.tsx',source,ts.ScriptTarget.Latest,true,kind),nodes=[];const attrValue=a=>{if(!a.initializer)return true;if(ts.isStringLiteral(a.initializer))return a.initializer.text;if(ts.isJsxExpression(a.initializer)&&a.initializer.expression&&ts.isStringLiteral(a.initializer.expression))return a.initializer.expression.text;return {expression:a.initializer.getText(sf)}};const visit=n=>{if(ts.isJsxElement(n)||ts.isJsxSelfClosingElement(n)){const opening=ts.isJsxElement(n)?n.openingElement:n,attributes={};for(const p of opening.attributes.properties)if(ts.isJsxAttribute(p))attributes[p.name.text]=attrValue(p);const tag=opening.tagName.getText(sf),children=ts.isJsxElement(n)?n.children:[],plain=children.filter(c=>ts.isJsxText(c)).map(c=>c.getText(sf)).join('').trim(),lc=sf.getLineAndCharacterOfPosition(n.getStart(sf));nodes.push(compactNode({tag,attributes,text:plain||null,style:{},start:n.getStart(sf),end:n.getEnd(),line:lc.line+1,column:lc.character+1,parser:'typescript',confidence:attributes['data-ui-id']?1:.94}));}ts.forEachChild(n,visit)};visit(sf);const diagnostics=ts.getPreEmitDiagnostics?[]:[];return {parser:'typescript',nodes,styleRules:fallbackMarkup(source).styleRules,diagnostics,astValidated:true,confidence:.96};}catch(error){const fb=fallbackMarkup(source);fb.diagnostics.push(`TypeScript compiler unavailable or parse failed: ${error.message}`);return fb;}
}
async function inspectVue(source){
  try{const sfc=await import('@vue/compiler-sfc');const parsed=sfc.parse(source,{sourceMap:false});const template=parsed.descriptor?.template?.content||'';let nodes=[];try{const dom=await import('@vue/compiler-dom');const ast=dom.parse(template,{comments:true}),offset=source.indexOf(template);genericWalk(ast,n=>{if(n?.type!==1||!n.tag)return;const attributes={};for(const p of n.props||[]){if(p.type===6)attributes[p.name]=p.value?.content??true;else if(p.type===7&&p.arg?.content)attributes[`:${p.arg.content}`]={expression:p.exp?.content||''};}const plain=(n.children||[]).filter(c=>c.type===2).map(c=>c.content).join('').trim();nodes.push(compactNode({tag:n.tag,attributes,text:plain||null,start:offset+(n.loc?.start?.offset||0),end:offset+(n.loc?.end?.offset||0),line:n.loc?.start?.line||null,column:n.loc?.start?.column||null,parser:'@vue/compiler-dom',confidence:attributes['data-ui-id']?1:.95}));});}catch{nodes=fallbackMarkup(template,'@vue/compiler-sfc').nodes}return {parser:'@vue/compiler-sfc',nodes,styleRules:fallbackMarkup(source).styleRules,diagnostics:(parsed.errors||[]).map(String),astValidated:true,confidence:.95};}catch(error){const fb=fallbackMarkup(source);fb.diagnostics.push(`Vue compiler unavailable or parse failed: ${error.message}`);return fb;}
}
async function inspectSvelte(source){
  try{const mod=await import('svelte/compiler'),ast=mod.parse(source),nodes=[];genericWalk(ast,n=>{const t=String(n?.type||'');if(!/(?:Element|Component)$/.test(t)||!n.name)return;const attributes={};for(const a of n.attributes||[]){if(a?.name)attributes[a.name]=literalAttr(a.value)??true;}const children=n.children||n.fragment?.nodes||[],plain=children.filter(c=>/Text/.test(String(c.type))).map(c=>c.data??c.raw??'').join('').trim(),p=posOf(n);nodes.push(compactNode({tag:n.name,attributes,text:plain||null,...p,parser:'svelte/compiler',confidence:attributes['data-ui-id']?1:.94}));});return {parser:'svelte/compiler',nodes:nodes.length?nodes:fallbackMarkup(source).nodes,styleRules:fallbackMarkup(source).styleRules,diagnostics:[],astValidated:true,confidence:.95};}catch(error){const fb=fallbackMarkup(source);fb.diagnostics.push(`Svelte compiler unavailable or parse failed: ${error.message}`);return fb;}
}

const PY_SCRIPT=String.raw`import ast,json,sys
src=sys.stdin.read(); out={'nodes':[],'diagnostics':[]}
lines=src.splitlines(True); offsets=[0]
for line in lines: offsets.append(offsets[-1]+len(line))
def ccol(line_no,byte_col):
    if not line_no or line_no<1 or line_no>len(lines): return 0
    raw=lines[line_no-1].encode('utf8')[:max(0,byte_col or 0)]
    return len(raw.decode('utf8','ignore'))
def span(n):
    sl=getattr(n,'lineno',None); el=getattr(n,'end_lineno',sl); sc=ccol(sl,getattr(n,'col_offset',0)); ec=ccol(el,getattr(n,'end_col_offset',0));
    return ((offsets[sl-1]+sc) if sl else None,(offsets[el-1]+ec) if el else None)
try: tree=ast.parse(src)
except Exception as e: out['diagnostics'].append(str(e)); print(json.dumps(out)); raise SystemExit

def name(n):
    if isinstance(n,ast.Name): return n.id
    if isinstance(n,ast.Attribute): return name(n.value)+'.'+n.attr
    return ''
def lit(n):
    try:return ast.literal_eval(n)
    except:return {'expression':ast.get_source_segment(src,n) or ''}
for n in ast.walk(tree):
    if isinstance(n,(ast.Assign,ast.AnnAssign)) and isinstance(getattr(n,'value',None),ast.Call):
        target=(n.targets[0] if isinstance(n,ast.Assign) and n.targets else n.target)
        if not isinstance(target,ast.Name): continue
        call=n.value; fn=name(call.func); attrs={k.arg:lit(k.value) for k in call.keywords if k.arg}; pos=[lit(a) for a in call.args]
        if fn.startswith(('tk.','ttk.','tkinter.')) or fn.startswith('ui.'):
            attrs['symbol']=target.id; st,en=span(n); out['nodes'].append({'kind':'call','tag':fn,'attributes':attrs,'text':attrs.get('text') if isinstance(attrs.get('text'),str) else (pos[0] if fn.startswith('ui.') and pos and isinstance(pos[0],str) else None),'style':{},'start':st,'end':en,'line':getattr(n,'lineno',None),'column':getattr(n,'col_offset',None),'dataUiId':None,'selectorPath':None,'symbolPath':target.id,'parser':'python-ast','confidence':1.0})
print(json.dumps(out))`;
function inspectPython(source,backend){const exe=process.env.PYTHON||process.env.PYTHON3||(process.platform==='win32'?'python':'python3'),r=spawnSync(exe,['-c',PY_SCRIPT],{input:String(source),encoding:'utf8',maxBuffer:10_000_000});if(r.status===0){try{return {parser:'python-ast',...JSON.parse(r.stdout),styleRules:[],astValidated:true,confidence:1}}catch{}}const fb={parser:'python-lexical',nodes:[],styleRules:[],diagnostics:[`Python AST unavailable: ${r.stderr||'python not found'}`],astValidated:false,confidence:.55};const re=/(?:^|\n)\s*([A-Za-z_]\w*)\s*=\s*(?:(?:tk|ttk|tkinter)\.)?([A-Za-z_]\w*)\s*\(([^\n]*)\)/g;let m;while((m=re.exec(source)))fb.nodes.push(compactNode({tag:m[2],attributes:{symbol:m[1]},symbolPath:m[1],parser:fb.parser,confidence:.65}));return fb;}

async function inspectLvgl(source){
  let validated=false,diagnostics=[],parser='portable-c';try{const ParserMod=await import('tree-sitter'),CMod=await import('tree-sitter-c'),Parser=ParserMod.default||ParserMod,C=CMod.default||CMod,p=new Parser();p.setLanguage(C);const tree=p.parse(source);validated=!tree.rootNode.hasError();parser='tree-sitter-c';if(!validated)diagnostics.push('tree-sitter reported C syntax errors.');}catch(error){diagnostics.push(`tree-sitter-c unavailable: ${error.message}`)}
  const nodes=[],re=/(?:lv_obj_t\s*\*\s*)?([A-Za-z_]\w*)\s*=\s*lv_([A-Za-z0-9_]+)_create\s*\(\s*([A-Za-z_]\w*|NULL)\s*\)/g;let m;while((m=re.exec(source)))nodes.push(compactNode({tag:`lv_${m[2]}`,attributes:{symbol:m[1],parent:m[3]},symbolPath:m[1],start:m.index,end:re.lastIndex,parser,confidence:validated?1:.78}));for(const n of nodes){const safe=n.symbolPath.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),tm=new RegExp(`lv_label_set_text\\s*\\(\\s*${safe}\\s*,\\s*\"((?:\\\\.|[^\"\\\\])*)\"`).exec(source);if(tm)n.text=tm[1].replace(/\\n/g,'\n').replace(/\\"/g,'"');const pm=new RegExp(`lv_obj_set_pos\\s*\\(\\s*${safe}\\s*,\\s*(-?\\d+)\\s*,\\s*(-?\\d+)`).exec(source);if(pm)Object.assign(n.style,{left:`${pm[1]}px`,top:`${pm[2]}px`});const sm=new RegExp(`lv_obj_set_size\\s*\\(\\s*${safe}\\s*,\\s*(-?\\d+)\\s*,\\s*(-?\\d+)`).exec(source);if(sm)Object.assign(n.style,{width:`${sm[1]}px`,height:`${sm[2]}px`});}return {parser,nodes,styleRules:[],diagnostics,astValidated:validated,confidence:validated?1:.78};
}

export async function inspectSourceAst({backend='astro',source='',relativePath=''}){const b=backend||'astro';let result;if(b==='astro')result=await inspectAstro(source);else if(b==='react'||b==='vanilla-ts')result=await inspectReact(source,relativePath||'Component.tsx');else if(b==='vue')result=await inspectVue(source);else if(b==='svelte')result=await inspectSvelte(source);else if(b==='tkinter'||b==='nicegui')result=inspectPython(source,b);else if(b==='lvgl')result=await inspectLvgl(source);else result=fallbackMarkup(source);return {backend:b,relativePath:safeRel(relativePath),fingerprint:fingerprint(source),...result};}
export async function parserAvailability(){const specs={'@astrojs/compiler-rs':'@astrojs/compiler-rs','@astrojs/compiler':'@astrojs/compiler',typescript:'typescript','@vue/compiler-sfc':'@vue/compiler-sfc','@vue/compiler-dom':'@vue/compiler-dom','svelte/compiler':'svelte/compiler','tree-sitter':'tree-sitter','tree-sitter-c':'tree-sitter-c'};const out={python:spawnSync(process.env.PYTHON||process.env.PYTHON3||(process.platform==='win32'?'python':'python3'),['--version'],{stdio:'ignore'}).status===0};for(const [key,spec] of Object.entries(specs)){try{await import(spec);out[key]=true}catch{out[key]=false}}return out;}


function normalizedChanges(changes=[]){return (changes||[]).filter(Boolean).map((c,i)=>({id:c.id||`${i}:${c.property||c.domain||'change'}`,domain:c.domain||((c.property==='text'||c.property==='content')?'text':'attribute'),property:String(c.property||''),previousValue:c.previousValue??null,value:c.value??''}))}
function findInspectionNode(inspection,identity={},nodeId=''){return (inspection?.nodes||[]).find(n=>(nodeId&&n.dataUiId===nodeId)||(identity.nodePath&&n.dataUiId===identity.nodePath)||(identity.symbolPath&&n.symbolPath===identity.symbolPath)||(identity.selectorPath&&n.selectorPath===identity.selectorPath))||null}
function openingTagRange(source,node){let start=Number.isFinite(node?.start)?node.start:-1,end=Number.isFinite(node?.end)?node.end:source.length;if(start<0)return null;let lt=source.indexOf('<',start);if(lt<0||lt>=end)return null;let quote='',brace=0,escape=false;for(let i=lt+1;i<Math.min(end,source.length);i++){const ch=source[i];if(escape){escape=false;continue}if(quote){if(ch==='\\'){escape=true;continue}if(ch===quote)quote='';continue}if(ch==='"'||ch==="'"){quote=ch;continue}if(ch==='{'){brace++;continue}if(ch==='}'&&brace){brace--;continue}if(ch==='>'&&!brace)return {start:lt,end:i+1}}return null}
function escapeAttr(value){return String(value).replace(/&/g,'&amp;').replace(/"/g,'&quot;')}
function patchOpeningTagLiteral(source,range,changes){let tag=source.slice(range.start,range.end),changed=false,diagnostics=[];for(const c of changes.filter(x=>x.domain==='attribute')){const key=String(c.property).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),quoted=new RegExp(`(\\s${key}\\s*=\\s*)(["'])([^"']*)\\2`),bare=new RegExp(`(\\s${key}\\s*=\\s*)([^\\s>]+)`);if(quoted.test(tag)){tag=tag.replace(quoted,`$1"${escapeAttr(c.value)}"`);changed=true}else if(bare.test(tag)){const m=tag.match(bare);if(m&&/[{(]/.test(m[2]))diagnostics.push(`${c.property}: expression-valued attribute is code-owned.`);else{tag=tag.replace(bare,`$1"${escapeAttr(c.value)}"`);changed=true}}else{const at=/\/>\s*$/.test(tag)?tag.lastIndexOf('/>'):tag.lastIndexOf('>');if(at>=0){tag=tag.slice(0,at)+` ${c.property}="${escapeAttr(c.value)}"`+tag.slice(at);changed=true}}}return {source:source.slice(0,range.start)+tag+source.slice(range.end),changed,diagnostics,delta:tag.length-(range.end-range.start)}}
function patchNodePlainText(source,node,openRange,change){if(!change)return {source,changed:false,diagnostics:[]};const end=Number.isFinite(node?.end)?Math.min(node.end,source.length):source.length,tag=String(node?.tag||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),closeRe=new RegExp(`<\\/${tag}\\s*>`,'g');closeRe.lastIndex=openRange.end;const close=closeRe.exec(source);if(!close||close.index>end)return {source,changed:false,diagnostics:['Plain-text closing tag was not found inside the AST node range.']};const inner=source.slice(openRange.end,close.index);if(/[<{]/.test(inner)||/}\s*$/.test(inner))return {source,changed:false,diagnostics:['Text contains child markup or an expression and remains code-owned.']};const value=String(change.value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');return {source:source.slice(0,openRange.end)+value+source.slice(close.index),changed:inner!==value,diagnostics:[]}}
function cssPropName(name){return String(name).replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`)}
function patchStyleRuleRange(source,rule,changes){if(!rule||!Number.isFinite(rule.start)||!Number.isFinite(rule.end))return {source,changed:false,diagnostics:['Mapped CSS rule has no source range.']};let block=source.slice(rule.start,rule.end),open=block.indexOf('{'),close=block.lastIndexOf('}');if(open<0||close<open)return {source,changed:false,diagnostics:['Mapped CSS rule is malformed.']};let body=block.slice(open+1,close),changed=false;for(const c of changes.filter(x=>x.domain==='style')){const prop=cssPropName(c.property),safe=prop.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),re=new RegExp(`(^|[;\\n\\r]\\s*)(${safe})\\s*:\\s*([^;}]*)`,'i'),value=String(c.value??'').trim();if(re.test(body)){const next=body.replace(re,(all,prefix,name)=>`${prefix}${name}: ${value}`);changed=changed||next!==body;body=next}else{const trimmed=body.replace(/\s*$/,'');body=`${trimmed}${trimmed&&!/[;\\n]\\s*$/.test(trimmed)?';':''}\\n  ${prop}: ${value};\\n`;changed=true}}const nextBlock=block.slice(0,open+1)+body+block.slice(close);return {source:source.slice(0,rule.start)+nextBlock+source.slice(rule.end),changed,diagnostics:[]}}
async function syntaxPatchWeb(source,inspection,node,identity,changes,backend,relativePath,nodeId){let out=source,diagnostics=[],changed=false,currentInspection=inspection,currentNode=node;const markup=changes.filter(c=>c.domain!=='style'),style=changes.filter(c=>c.domain==='style');if(style.length){const selector=identity.selectorPath||currentNode.selectorPath,rule=(currentInspection.styleRules||[]).find(r=>selector&&String(r.selector||'').split(',').map(x=>x.trim()).includes(selector));if(!rule)diagnostics.push('No exact CSS selector rule is mapped to this node.');else{const styleResult=patchStyleRuleRange(out,rule,style);out=styleResult.source;changed=changed||styleResult.changed;diagnostics.push(...styleResult.diagnostics);if(styleResult.changed&&markup.length){currentInspection=await inspectSourceAst({backend,source:out,relativePath});if(!currentInspection.astValidated)diagnostics.push('Source could not be revalidated after the style edit.');else{currentNode=findInspectionNode(currentInspection,identity,nodeId);if(!currentNode)diagnostics.push('Mapped node disappeared after the style edit.')}}}}if(markup.length&&currentNode){const range=openingTagRange(out,currentNode);if(!range)diagnostics.push('AST node opening tag range could not be resolved.');else{const attrResult=patchOpeningTagLiteral(out,range,markup);out=attrResult.source;changed=changed||attrResult.changed;diagnostics.push(...attrResult.diagnostics);const text=markup.find(c=>c.domain==='text'||c.property==='text'||c.property==='content');if(text){const adjustedNode={...currentNode,end:Number.isFinite(currentNode.end)?currentNode.end+attrResult.delta:currentNode.end},adjustedRange={start:range.start,end:range.end+attrResult.delta},textResult=patchNodePlainText(out,adjustedNode,adjustedRange,text);out=textResult.source;changed=changed||textResult.changed;diagnostics.push(...textResult.diagnostics)}}}return {ok:changed&&diagnostics.length===0,source:out,diagnostics}}
function syntaxPatchPython(source,inspection,node,identity,changes,backend){const symbol=identity.symbolPath||node?.symbolPath;if(!symbol)return {ok:false,source,diagnostics:['Python symbol mapping is missing.']};let out=source,changed=false,diagnostics=[];const text=changes.find(c=>c.domain==='text'||c.property==='text'),target=(inspection.nodes||[]).find(n=>n.symbolPath===symbol&&Number.isFinite(n.start)&&Number.isFinite(n.end))||node;if(text&&target&&Number.isFinite(target.start)&&Number.isFinite(target.end)){let segment=out.slice(target.start,target.end);const key=backend==='nicegui'?null:'text';if(backend==='nicegui'){const re=/(["'])(?:\\.|(?!\1).)*\1/;if(re.test(segment)){const q=(segment.match(re)||['"'])[0][0],safe=String(text.value).replaceAll('\\','\\\\').replaceAll(q,`\\${q}`);segment=segment.replace(re,`${q}${safe}${q}`);out=out.slice(0,target.start)+segment+out.slice(target.end);changed=true}else diagnostics.push('NiceGUI text is not a literal.')}else{const re=/(\btext\s*=\s*)(["'])(?:\\.|(?!\2).)*\2/;if(re.test(segment)){segment=segment.replace(re,`$1${JSON.stringify(String(text.value))}`);out=out.slice(0,target.start)+segment+out.slice(target.end);changed=true}else diagnostics.push('Tkinter text is not a literal keyword argument.')}}const unsupported=changes.filter(c=>c!==text);if(unsupported.length)diagnostics.push(`${unsupported.length} non-text Python change(s) require the conservative symbol patch adapter.`);return {ok:changed&&diagnostics.length===0,source:out,diagnostics}}
function syntaxPatchLvgl(source,inspection,node,identity,changes){if(!inspection.astValidated)return {ok:false,source,diagnostics:['tree-sitter did not validate this C source.']};const symbol=identity.symbolPath||node?.symbolPath;if(!symbol)return {ok:false,source,diagnostics:['LVGL symbol mapping is missing.']};let out=source,changed=false,diagnostics=[],safe=String(symbol).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const text=changes.find(c=>c.domain==='text'||c.property==='text');if(text){const re=new RegExp(`(lv_label_set_text\\s*\\(\\s*${safe}\\s*,\\s*)"(?:\\\\.|[^"\\\\])*"`);if(re.test(out)){out=out.replace(re,`$1${JSON.stringify(String(text.value))}`);changed=true}else diagnostics.push('LVGL label setter literal not found.')}const style=Object.fromEntries(changes.filter(c=>c.domain==='style').map(c=>[c.property,c.value]));if('left'in style||'top'in style){const re=new RegExp(`(lv_obj_set_pos\\s*\\(\\s*${safe}\\s*,\\s*)-?\\d+\\s*,\\s*-?\\d+`);if(re.test(out)){out=out.replace(re,`$1${parseInt(style.left??0,10)||0}, ${parseInt(style.top??0,10)||0}`);changed=true}}if('width'in style||'height'in style){const re=new RegExp(`(lv_obj_set_size\\s*\\(\\s*${safe}\\s*,\\s*)-?\\d+\\s*,\\s*-?\\d+`);if(re.test(out)){out=out.replace(re,`$1${parseInt(style.width??100,10)||100}, ${parseInt(style.height??30,10)||30}`);changed=true}}return {ok:changed&&diagnostics.length===0,source:out,diagnostics}}
export async function buildSyntaxPatchPlan({backend='astro',source='',relativePath='',sourceIdentity={},nodeId='',changes=[]}={}){const inspection=await inspectSourceAst({backend,source,relativePath}),identity={...sourceIdentity},node=findInspectionNode(inspection,identity,nodeId),normalized=normalizedChanges(changes);if(!node)return {ok:false,message:'Syntax adapter could not resolve the mapped source node.',inspection};if(!inspection.astValidated)return {ok:false,message:`${inspection.parser} did not provide a validated syntax tree.`,inspection};let patched;if(['astro','react','vue','svelte','vanilla-js','vanilla-ts'].includes(backend))patched=await syntaxPatchWeb(String(source),inspection,node,identity,normalized,backend,relativePath,nodeId);else if(backend==='tkinter'||backend==='nicegui')patched=syntaxPatchPython(String(source),inspection,node,identity,normalized,backend);else if(backend==='lvgl')patched=syntaxPatchLvgl(String(source),inspection,node,identity,normalized);else return {ok:false,message:`No syntax patch adapter for ${backend}.`,inspection};if(!patched.ok)return {ok:false,message:'Validated syntax adapter found no safely editable literal/range.',diagnostics:patched.diagnostics,inspection};const strategy=identity.symbolPath?'ast-exact-symbol':node.dataUiId?'ast-exact-data-ui-id':identity.selectorPath?'ast-exact-selector':'ast-exact-range',matchedTarget=identity.symbolPath||node.dataUiId||identity.selectorPath||node.tag;return {ok:true,inspection,plan:{backend,kind:'syntax',relativePath:safeRel(relativePath),targetLabel:matchedTarget,existingSource:String(source),nextSource:patched.source,changes:normalized,warnings:patched.diagnostics||[],diagnostics:[],dryRun:true,confidence:Math.min(1,Number(node.confidence||inspection.confidence||.95)),resolution:{strategy,requestedTarget:identity.selectorPath||identity.nodePath||identity.symbolPath||nodeId,matchedTarget},baselineFingerprint:fingerprint(source),sourceIdentity:identity,nodeId:nodeId||identity.nodePath||node.dataUiId||'',selectorPath:identity.selectorPath||node.selectorPath||'',astAnchor:{exact:true,parser:inspection.parser,start:node.start,end:node.end}}}}

class WorkspaceWatcher{
  constructor(root){this.root=path.resolve(root);this.watchers=new Map();this.events=[];this.seq=0;this.startedAt=new Date().toISOString();this.scanDir(this.root);}
  ignored(p){return safeRel(path.relative(this.root,p)).split('/').some(x=>IGNORE_DIRS.has(x));}
  scanDir(dir){if(this.ignored(dir))return;let entries=[];try{entries=fs.readdirSync(dir,{withFileTypes:true})}catch{return}if(!this.watchers.has(dir)){try{const w=fs.watch(dir,(event,name)=>this.onEvent(dir,event,name));w.on('error',()=>this.closeDir(dir));this.watchers.set(dir,w)}catch{}}for(const e of entries)if(e.isDirectory())this.scanDir(path.join(dir,e.name));}
  closeDir(dir){try{this.watchers.get(dir)?.close()}catch{}this.watchers.delete(dir)}
  onEvent(dir,event,name){if(!name)return;const full=path.join(dir,String(name));if(this.ignored(full))return;try{if(fs.statSync(full).isDirectory()){this.scanDir(full);return}}catch{}if(!WATCH_EXTS.has(path.extname(full).toLowerCase()))return;const relativePath=safeRel(path.relative(this.root,full)),row={id:++this.seq,event,relativePath,at:new Date().toISOString()};this.events.push(row);if(this.events.length>1000)this.events.splice(0,this.events.length-1000);}
  poll(after=0){return {token:this.seq,events:this.events.filter(e=>e.id>Number(after||0)),running:true,startedAt:this.startedAt};}
  close(){for(const w of this.watchers.values())try{w.close()}catch{}this.watchers.clear();}
}

const PROFILES={astro:{command:'npm',args:['run','dev','--','--host','127.0.0.1','--port','4321'],url:'http://127.0.0.1:4321'},react:{command:'npm',args:['run','dev','--','--host','127.0.0.1','--port','5173'],url:'http://127.0.0.1:5173'},vue:{command:'npm',args:['run','dev','--','--host','127.0.0.1','--port','5173'],url:'http://127.0.0.1:5173'},svelte:{command:'npm',args:['run','dev','--','--host','127.0.0.1','--port','5173'],url:'http://127.0.0.1:5173'},'vanilla-js':{command:'npm',args:['run','dev','--','--host','127.0.0.1','--port','5173'],url:'http://127.0.0.1:5173'},'vanilla-ts':{command:'npm',args:['run','dev','--','--host','127.0.0.1','--port','5173'],url:'http://127.0.0.1:5173'},tkinter:{command:process.platform==='win32'?'python':'python3',args:['main.py'],url:''},nicegui:{command:process.platform==='win32'?'python':'python3',args:['main.py'],url:'http://127.0.0.1:8080'},lvgl:{command:'',args:[],url:''}};

export class RoundTripNodeRuntime{
  constructor(){this.watcher=null;this.watcherRoot='';this.preview=null;this.previewRoot='';this.previewBackend='';}
  startWatcher(root){const resolved=path.resolve(root);if(this.watcher&&this.watcherRoot===resolved)return this.watcher.poll(0);this.stopWatcher();this.watcher=new WorkspaceWatcher(resolved);this.watcherRoot=resolved;return this.watcher.poll(0)}
  stopWatcher(){this.watcher?.close();this.watcher=null;this.watcherRoot='';return {running:false}}
  stopPreview(){if(this.preview)try{this.preview.kill('SIGTERM')}catch{}this.preview=null;this.previewRoot='';this.previewBackend='';return {running:false}}
  startPreview(root,backend){this.stopPreview();const profile=PROFILES[backend]||PROFILES.astro;if(!profile.command)throw new Error(`No managed preview command for ${backend}. Configure an external simulator command.`);const command=process.platform==='win32'&&profile.command==='npm'?'npm.cmd':profile.command;this.preview=spawn(command,profile.args,{cwd:root,env:{...process.env,NO_COLOR:'1'},stdio:['ignore','pipe','pipe']});this.previewRoot=root;this.previewBackend=backend;this.preview.on('exit',()=>{this.preview=null});return {running:true,backend,url:profile.url,command:[command,...profile.args].join(' ')}}
  async handle(route,data,root){const r=String(route).replace(/^\/?(?:api\/)?roundtrip\//,'');if(r==='health')return {available:true,parsers:await parserAvailability()};if(!root)throw new Error('No workspace is open');if(r==='inspect'){const relativePath=safeRel(data.relativePath),source=fs.readFileSync(safeJoin(root,relativePath),'utf8');return inspectSourceAst({backend:data.backend,source,relativePath})}if(r==='plan'){const relativePath=safeRel(data.relativePath),source=fs.readFileSync(safeJoin(root,relativePath),'utf8'),actual=fingerprint(source);if(data.baselineFingerprint&&data.baselineFingerprint!==actual)throw new Error(`Stale source: expected ${data.baselineFingerprint}, found ${actual}`);return buildSyntaxPatchPlan({backend:data.backend,source,relativePath,sourceIdentity:data.sourceIdentity||{},nodeId:data.nodeId||'',changes:data.changes||[]})}if(r==='apply'){const relativePath=safeRel(data.relativePath),fp=safeJoin(root,relativePath),current=fs.readFileSync(fp,'utf8'),actual=fingerprint(current);if(data.baselineFingerprint&&data.baselineFingerprint!==actual)throw new Error(`Stale source: expected ${data.baselineFingerprint}, found ${actual}`);const tmp=`${fp}.astro-ui-tmp-${process.pid}`;fs.writeFileSync(tmp,String(data.nextSource),'utf8');fs.renameSync(tmp,fp);return {ok:true,relativePath,fingerprint:fingerprint(data.nextSource),bytes:Buffer.byteLength(String(data.nextSource))}}if(r==='watch/start')return this.startWatcher(root);if(r==='watch/poll')return this.watcher&&this.watcherRoot===path.resolve(root)?this.watcher.poll(data.after||0):this.startWatcher(root);if(r==='watch/stop')return this.stopWatcher();if(r==='preview/start')return this.startPreview(root,data.backend||'astro');if(r==='preview/stop')return this.stopPreview();throw new Error(`Unknown round-trip route: ${route}`)}
  dispose(){this.stopWatcher();this.stopPreview();}
}

export function createRoundTripNodeRuntime(){return new RoundTripNodeRuntime();}
