import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const IGNORE=new Set(['node_modules','.git','dist','.astro','.vercel','.netlify']);
export function safeRoot(p){const abs=path.resolve(String(p||''));if(!fs.existsSync(abs)||!fs.statSync(abs).isDirectory())throw new Error('Workspace directory does not exist');return abs;}
export function safeJoin(root,rel){const p=path.resolve(root,String(rel||''));if(p!==root&&!p.startsWith(root+path.sep))throw new Error('Path escapes workspace');return p;}
function walkFiles(root,dir=root,out=[]){for(const ent of fs.readdirSync(dir,{withFileTypes:true})){if(IGNORE.has(ent.name))continue;const p=path.join(dir,ent.name);if(ent.isDirectory())walkFiles(root,p,out);else if(ent.isFile()&&/\.(astro|tsx?|jsx?|mjs|cjs|svelte|vue|json|mdx?|css)$/i.test(ent.name))out.push(path.relative(root,p).replaceAll(path.sep,'/'));}return out;}
function parseTypedProps(body=''){const out=[];const re=/([A-Za-z_$][\w$]*)\s*(\?)?\s*:\s*([^;\n}]+)/g;let x;while((x=re.exec(body))){const rawType=x[3].trim();const options=[...rawType.matchAll(/[\"']([^\"']+)[\"']/g)].map(v=>v[1]);out.push({name:x[1],optional:Boolean(x[2]),type:/\bboolean\b/.test(rawType)?'boolean':/\bnumber\b/.test(rawType)?'number':options.length?'enum':'string',options,rawType});}return out;}
function inferProps(source){const m=source.match(/interface\s+Props\s*\{([\s\S]*?)\}/m)||source.match(/type\s+Props\s*=\s*\{([\s\S]*?)\}/m);return m?parseTypedProps(m[1]):[];}
function componentName(rel){return (path.basename(rel).replace(/\.(astro|tsx?|jsx?|vue|svelte)$/i,'')||'Component').replace(/[^A-Za-z0-9_$]/g,'_');}
function scanFrameworkComponent(rel,source){const ext=path.extname(rel).toLowerCase(),name=componentName(rel);if(ext==='.astro')return null;
  if(ext==='.tsx'||ext==='.ts'||ext==='.jsx'||ext==='.js') {let props=inferProps(source);if(!props.length){const m=source.match(/(?:function|const)\s+[A-Za-z_$][\w$]*\s*(?:=\s*)?\(?\s*\{[^}]*\}\s*:\s*\{([\s\S]*?)\}/m);if(m)props=parseTypedProps(m[1]);}const children=props.some(p=>p.name==='children');return {relativePath:rel,kind:'component',framework:'react',name,symbol:name,props,slots:children?['default']:[],uiIds:[...source.matchAll(/data-ui-id=[\"']([^\"']+)[\"']/g)].map(m=>m[1])};}
  if(ext==='.vue'){let props=[];const gen=source.match(/defineProps\s*<\s*\{([\s\S]*?)\}\s*>/m);if(gen)props=parseTypedProps(gen[1]);else{const obj=source.match(/defineProps\s*\(\s*\{([\s\S]*?)\}\s*\)/m);if(obj)props=[...obj[1].matchAll(/([A-Za-z_$][\w$]*)\s*:/g)].map(m=>({name:m[1],optional:true,type:'string',options:[],rawType:'unknown'}));}const slots=[...source.matchAll(/<slot(?:\s+name=[\"']([^\"']+)[\"'])?[^>]*>/g)].map(m=>m[1]||'default');return {relativePath:rel,kind:'component',framework:'vue',name,symbol:name,props,slots:[...new Set(slots)],uiIds:[]};}
  if(ext==='.svelte'){const props=[];for(const m of source.matchAll(/export\s+let\s+([A-Za-z_$][\w$]*)(?:\s*:\s*([^=;\n]+))?/g)){const rawType=(m[2]||'string').trim();props.push({name:m[1],optional:true,type:/boolean/.test(rawType)?'boolean':/number/.test(rawType)?'number':'string',options:[],rawType});}const destruct=source.match(/let\s*\{([\s\S]*?)\}\s*(?::[^=]+)?=\s*\$props\s*\(\s*\)/m);if(destruct)for(const part of destruct[1].split(',')){const n=part.trim().match(/^([A-Za-z_$][\w$]*)/);if(n&&!props.some(p=>p.name===n[1]))props.push({name:n[1],optional:true,type:'string',options:[],rawType:'unknown'});}const slots=/<slot(?:\s|>)/.test(source)?['default']:[];return {relativePath:rel,kind:'component',framework:'svelte',name,symbol:name,props,slots,uiIds:[]};}
  return null;}

async function compilerAst(source){try{const mod=await import('@astrojs/compiler-rs');const parsed=mod.parse(source);return parsed?.ast||null}catch{return null}}
export async function scanWorkspace(root){const files=walkFiles(root);const astro=[],components=[];for(const rel of files){if(!/\.(astro|tsx?|jsx?|vue|svelte)$/i.test(rel))continue;const source=fs.readFileSync(path.join(root,rel),'utf8');if(rel.endsWith('.astro')){const props=inferProps(source);const slots=[...source.matchAll(/<slot(?:\s+name=[\"']([^\"']+)[\"'])?\s*\/?\s*>/g)].map(m=>m[1]||'default');const item={relativePath:rel,kind:rel.startsWith('src/pages/')?'page':'component',framework:'astro',name:componentName(rel),symbol:componentName(rel),props,slots:[...new Set(slots)],uiIds:[...source.matchAll(/data-ui-id=[\"']([^\"']+)[\"']/g)].map(m=>m[1]),astAvailable:Boolean(await compilerAst(source))};astro.push(item);if(item.kind==='component')components.push(item);}else if(!rel.startsWith('src/pages/')){const item=scanFrameworkComponent(rel,source);if(item)components.push(item);}}return{rootPath:root,files,astro,components,packageJson:readJson(root,'package.json'),astroConfig:files.find(f=>/^astro\.config\./.test(f))||'',git:isGit(root),scannedAt:new Date().toISOString()};}
function readJson(root,rel){try{return JSON.parse(fs.readFileSync(path.join(root,rel),'utf8'))}catch{return null}}
function isGit(root){return fs.existsSync(path.join(root,'.git'))||spawnSync('git',['-C',root,'rev-parse','--is-inside-work-tree'],{encoding:'utf8'}).status===0}
export function git(root,args){const r=spawnSync('git',['-C',root,...args],{encoding:'utf8'});if(r.status!==0)throw new Error((r.stderr||r.stdout||'git command failed').trim());return r.stdout;}
export function readFile(root,rel){return fs.readFileSync(safeJoin(root,rel),'utf8')}
export function writeFile(root,rel,content){const p=safeJoin(root,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,String(content),'utf8');return{relativePath:rel,bytes:Buffer.byteLength(String(content))}}
