import assert from 'node:assert/strict';
import { createProject, createNode, makeId } from '../standalone/js/model.js';
import { generateAstroProject } from '../standalone/js/astro-exporter.js';

const p=createProject();
p.name='export-test';
p.variables=[{id:'s1',name:'message',type:'string',initial:'Initial'}];
const compRoot=createNode('card',{name:'FeatureCardRoot'});
compRoot.children.push(createNode('heading',{props:{text:'Fallback',level:'3'},bindings:{text:'props.title'}}));
compRoot.children.push(createNode('slot',{props:{name:''}}));
const comp={id:'comp-1',name:'FeatureCard',filename:'FeatureCard.astro',description:'',props:[{name:'title',type:'string',default:'Default title'}],root:compRoot};
p.components.push(comp);
const inst=createNode('componentInstance',{props:{definitionId:comp.id,propValues:{title:'Instance title'}}});
inst.children.push(createNode('text',{props:{text:'Slotted body'}}));
const dynamic=createNode('text',{props:{text:'ignored'},bindings:{text:'state.message'}});
dynamic.actions=[{id:makeId('act'),event:'click',type:'setState',value:'message=Changed',target:'',condition:''}];
p.pages[0].root.children.push(inst,dynamic);
p.pages.push({id:'nested-page',name:'Docs',route:'/docs/intro',filename:'docs/intro/index.astro',seo:{title:'Docs',description:'',canonical:'',ogImage:''},root:createNode('page',{props:{title:'Docs',description:''}})});
p.assets.push({id:'asset-1',name:'x.txt',filename:'x.txt',mime:'text/plain',size:2,base64:'aGk=',dataUrl:'data:text/plain;base64,aGk='});
const files=generateAstroProject(p);
assert.ok(files['src/components/FeatureCard.astro'].includes('interface Props'));
assert.ok(files['src/components/FeatureCard.astro'].includes('props.title'));
assert.ok(files['src/pages/index.astro'].includes('<FeatureCard title={"Instance title"}>'));
assert.ok(files['src/scripts/ui-runtime.ts'].includes('setState'));
assert.ok(files['src/styles/global.css'].includes('--color-primary'));
assert.ok(files['src/pages/docs/intro/index.astro'].includes("../../../layouts/BaseLayout.astro"));
assert.ok(files['public/assets/x.txt'] instanceof Uint8Array);
assert.equal(new TextDecoder().decode(files['public/assets/x.txt']),'hi');
console.log('exporter.test: OK');
