import assert from 'node:assert/strict';
import { createProject, createNode } from '../standalone/js/model.js';
import { ensureResearchModel, ensureNodeResearch, registerExternalComponent, createNodeState, createContainerRule, createTimelineTrack, addContentCollection, addCollectionEntry, createRecordedTest, addTestStep, createStory } from '../standalone/js/research-features.js';
import { generateAstroProject } from '../standalone/js/astro-exporter.js';

const p=createProject(); ensureResearchModel(p); p.settings.viewTransitions=true;
p.theme.themes.default.tokens['space-4']='16px';
const ext=registerExternalComponent(p,{name:'Fancy',symbol:'Fancy',importPath:'../components/Fancy.astro',framework:'astro',props:[{name:'title',type:'string'}]});
const external=createNode('externalComponent',{props:{descriptorId:ext.id,symbol:'Fancy',importPath:'../components/Fancy.astro',framework:'astro',client:'none',propsJson:'{"title":"Hi"}'}});
ensureNodeResearch(external);
const state=createNodeState(external,'active'); state.style.opacity='1';
const cq=createContainerRule(external); cq.containerName='card'; cq.minWidth='360px'; cq.style.display='grid';
const tr=createTimelineTrack(external,'opacity');tr.keyframes[0].value='0';tr.keyframes[1].value='1';external.timeline.duration=300; external.timeline.trigger='load';
p.pages[0].root.children.push(external);
const col=addContentCollection(p,'posts');col.schema=[{name:'title',type:'string',required:true},{name:'featured',type:'boolean',required:false}];addCollectionEntry(col,{title:'Hello',featured:true});
const repeater=createNode('repeater',{props:{source:'posts',itemAlias:'item',filter:'',sort:'',limit:'3'}});repeater.children.push(createNode('text',{bindings:{text:'item.data.title'}}));p.pages[0].root.children.push(repeater);
const comp={id:'c1',name:'Card',filename:'Card.astro',description:'',props:[],root:createNode('card'),variants:[],stories:[]};p.components.push(comp);createStory(comp,'Desktop');
const test=createRecordedTest(p,'Home smoke');addTestStep(test,'click',external.id,'');
const files=generateAstroProject(p);
assert.ok(files['src/styles/global.css'].includes('@container card / (min-width: 360px)'));
assert.ok(files['src/styles/global.css'].includes('@keyframes ui-animation-'));
assert.ok(files['src/pages/index.astro'].includes("import Fancy from '../components/Fancy.astro'"));
assert.ok(files['src/pages/index.astro'].includes('getCollection("posts")'));
assert.ok(files['src/pages/index.astro'].includes('item.data.title'));
assert.ok(files['src/layouts/BaseLayout.astro'].includes('ClientRouter'));
assert.ok(files['src/content.config.ts'].includes("defineCollection"));
assert.ok(files['src/content/posts/entry-1.json'].includes('Hello'));
assert.ok(files['tokens/design-tokens.json'].includes('$schema'));
assert.ok(files['tests/ui-designer.tests.json'].includes('Home smoke'));
assert.ok(files['tests/ui-designer.tests.json'].includes('Desktop'));
assert.ok(files['designer-source-map.json']);
assert.ok(files['component-lab/portable-stories.json'].includes('Card'));
assert.ok(files['component-lab/component-manifest.json'].includes('astro-ui-component-manifest'));
assert.ok(files['component-lab/docs/Card.md'].includes('# Card'));
assert.ok(files['component-lab/test-results.json']);
console.log('export-research.test: OK');
