import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('../standalone/js/app.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../standalone/index.html',import.meta.url),'utf8');
const client=fs.readFileSync(new URL('../standalone/js/workspace-client.js',import.meta.url),'utf8');
const launcher=fs.readFileSync(new URL('../launch-designer.mjs',import.meta.url),'utf8');
const ext=fs.readFileSync(new URL('../vscode-extension/extension.js',import.meta.url),'utf8');
const bridge=fs.readFileSync(new URL('../standalone/js/roundtrip-app-bridge.js',import.meta.url),'utf8');
assert.match(html,/id="import-project-btn"/,'top toolbar must expose project import');
assert.match(app,/workspace\.importExisting/,'project import must be a command/hotkey target');
assert.match(app,/Ctrl\+Shift\+I/,'project import must have a default hotkey');
assert.match(app,/showDirectoryPicker|webkitdirectory/,'browser fallback must browse a directory');
assert.match(app,/data-import-backend/,'import review must allow adapter override');
assert.match(client,/workspace\/browse/,'workspace client must expose native browse route');
assert.match(launcher,/workspace\/browse/,'standalone host must implement native browse route');
assert.match(ext,/workspace\/browse/,'VS Code host must implement native browse route');
assert.match(ext,/showOpenDialog/,'VS Code browse uses native folder chooser');
assert.match(bridge,/async function detectWorkspace/);
assert.match(bridge,/async function importFiles/);
assert.match(bridge,/analyzeFiles/);
assert.equal(app,fs.readFileSync(new URL('../vscode-extension/designer/js/app.js',import.meta.url),'utf8'),'VS Code app mirror must match');
console.log('project-import-ui.test.mjs passed');
