import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('standalone/index.html','utf8');
const app=fs.readFileSync('standalone/js/app.js','utf8');
const css=fs.readFileSync('standalone/styles.css','utf8');
const wb=fs.readFileSync('standalone/js/functional-workbenches.js','utf8');
assert.match(html,/id="simulation-mode-btn"/);
assert.match(html,/id="simulation-pane"/);
assert.match(html,/id="simulation-root"/);
assert.match(html,/data-bottom-tab="simulation"/);
assert.match(app,/function renderSimulationPane\(/);
assert.match(app,/function renderSimulationNode\(/);
assert.match(app,/function simulationHasEvent\(/);
assert.match(app,/view\.simulate/);
assert.match(app,/defaultBindings:\['F7'\]/);
assert.match(app,/simulation_start|startSimulation/);
assert.match(app,/navigateSimulationBack/);
assert.match(wb,/state\.bottomTab==='simulation'/);
assert.match(css,/\.simulation-workspace|\.simulation-pane/);
console.log('simulation-ui.test.mjs passed');
