import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('../standalone/js/app.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../standalone/styles.css',import.meta.url),'utf8');
const vsApp=fs.readFileSync(new URL('../vscode-extension/designer/js/app.js',import.meta.url),'utf8');
const vsCss=fs.readFileSync(new URL('../vscode-extension/designer/styles.css',import.meta.url),'utf8');
assert.match(app,/import \{ installTooltipSystem \} from '\.\/tooltips\.js'/);
assert.match(app,/installTooltipSystem\(\)/);
assert.match(app,/2\.17\.2-direct-manipulation/);
assert.match(css,/\.designer-tooltip\{/);
assert.match(css,/z-index:12000/);
assert.equal(app,vsApp,'VS Code app mirror must match standalone app');
assert.equal(css,vsCss,'VS Code CSS mirror must match standalone CSS');
assert.equal(fs.readFileSync(new URL('../standalone/js/tooltips.js',import.meta.url),'utf8'),fs.readFileSync(new URL('../vscode-extension/designer/js/tooltips.js',import.meta.url),'utf8'));
console.log('tooltips-app-integration.test.mjs passed');
