// Generated by Astro UI Designer. Queries execute in your app, not through a hosted visual-builder proxy.
export const uiQueries = {
} as const;
export type UiQueryName = keyof typeof uiQueries;
export async function runUiQuery(name: UiQueryName, ctx: Record<string, unknown> = {}) { return uiQueries[name](ctx as never); }
 