#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import readline from 'node:readline';
import { validateProject } from '../../../standalone/js/validator.js';import { generateAstroProject } from '../../../standalone/js/astro-exporter.js';
const root=path.resolve(process.env.ASTRO_UI_PROJECT_ROOT||process.cwd());
const projectPath=()=>{for(const n of ['designer-project.json','.astro-ui.json']){const p=path.join(root,n);if(fs.existsSync(p))return p}return null};
function project(){const p=projectPath();if(!p)return null;return JSON.parse(fs.readFileSync(p,'utf8'))}
const tools=[{name:'project_summary',description:'Summarize the Astro UI Designer project',inputSchema:{type:'object',properties:{}}},{name:'validate_project',description:'Validate the project model',inputSchema:{type:'object',properties:{}}},{name:'export_astro',description:'Generate ordinary Astro source files into a contained output directory',inputSchema:{type:'object',properties:{outputDir:{type:'string'}}}}];
function safeOut(rel='hermes-export'){const p=path.resolve(root,rel);if(p!==root&&!p.startsWith(root+path.sep))throw new Error('Output must stay inside the project root');return p}
async function call(name,args={}){const p=project();if(!p)throw new Error('No designer-project.json or .astro-ui.json found in project root');if(name==='project_summary')return {name:p.name||'',schemaVersion:p.schemaVersion,pages:p.pages?.length||0,components:p.components?.length||0,assets:p.assets?.length||0,sourceFiles:p.workspace?.files?.length||0};if(name==='validate_project')return {issues:validateProject(p)};if(name==='export_astro'){const out=safeOut(args.outputDir||'hermes-export'),files=generateAstroProject(p);for(const [rel,text] of Object.entries(files)){const f=path.join(out,rel);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,text)}return {outputDir:path.relative(root,out),files:Object.keys(files)}}throw new Error(`Unknown tool: ${name}`)}
function reply(id,result,error=null){process.stdout.write(JSON.stringify(error?{jsonrpc:'2.0',id,error:{code:-32000,message:error.message||String(error)}}:{jsonrpc:'2.0',id,result})+'\n')}
const rl=readline.createInterface({input:process.stdin,crlfDelay:Infinity});rl.on('line',async line=>{let m;try{m=JSON.parse(line)}catch{return}try{if(m.method==='initialize')return reply(m.id,{protocolVersion:m.params?.protocolVersion||'2025-11-25',capabilities:{tools:{}},serverInfo:{name:'astro-ui-designer',version:'2.17.0'}});if(m.method==='tools/list')return reply(m.id,{tools});if(m.method==='tools/call')return reply(m.id,{content:[{type:'text',text:JSON.stringify(await call(m.params?.name,m.params?.arguments||{}),null,2)}]});if(m.method==='ping')return reply(m.id,{});if(m.id!=null)reply(m.id,null,new Error(`Unknown method: ${m.method}`))}catch(e){if(m.id!=null)reply(m.id,null,e)}});
