import { uiAnimationDefinitions } from './ui-animation-definitions';

type UIAction={event?:string;type?:string;target?:string;value?:string;condition?:string};
type UIAnimationPayload={engine?:'css'|'waapi';trigger?:string;keyframes?:Keyframe[];options?:Record<string,any>;playbackRate?:number;reducedMotion?:'disable'|'shorten'|'allow';scroll?:Record<string,string>};
const state:Record<string,any>={
  "menuOpen": false,
  "message": "Hello from state"
};
const animationStore=new WeakMap<HTMLElement,Animation>();
function target(id?:string){return id?document.querySelector<HTMLElement>(`[data-ui-id="${CSS.escape(id)}"]`):null;}
function interpolate(v=''){return v.replace(/\{\{state\.([A-Za-z_$][\w$]*)\}\}/g,(_,k)=>String(state[k]??''));}
function conditionOk(c=''){if(!c)return true;const m=c.match(/^state\.([A-Za-z_$][\w$]*)\s*(===|==|!==|!=)?\s*(.*)$/);if(!m)return true;const val=state[m[1]];if(!m[2])return Boolean(val);let rhs=m[3].trim().replace(/^['"]|['"]$/g,'');return (m[2]==='!='||m[2]==='!==')?String(val)!==rhs:String(val)===rhs;}
function refreshVisibility(){document.querySelectorAll<HTMLElement>('[data-ui-visible-if]').forEach(el=>{const c=el.dataset.uiVisibleIf||'';el.hidden=!conditionOk(c);});}
function refreshBindings(){document.querySelectorAll<HTMLElement>('[data-ui-bind-text]').forEach(el=>{const k=el.dataset.uiBindText||'';el.textContent=String(state[k]??'');});document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('[data-ui-bind-value]').forEach(el=>{const k=el.dataset.uiBindValue||'';el.value=String(state[k]??'');});document.querySelectorAll<HTMLInputElement>('[data-ui-bind-checked]').forEach(el=>{const k=el.dataset.uiBindChecked||'';el.checked=Boolean(state[k]);});document.querySelectorAll<HTMLButtonElement|HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('[data-ui-bind-disabled]').forEach(el=>{const k=el.dataset.uiBindDisabled||'';el.disabled=Boolean(state[k]);});document.querySelectorAll<HTMLImageElement>('[data-ui-bind-src]').forEach(el=>{const k=el.dataset.uiBindSrc||'';el.src=String(state[k]??'');});document.querySelectorAll<HTMLAnchorElement>('[data-ui-bind-href]').forEach(el=>{const k=el.dataset.uiBindHref||'';el.href=String(state[k]??'');});refreshVisibility();}
function animationPayload(el:HTMLElement):UIAnimationPayload|null{const id=el.dataset.uiAnimationId||'';return (uiAnimationDefinitions as Record<string,UIAnimationPayload>)[id]||null}
function makeWaapi(el:HTMLElement,restart=true){const p=animationPayload(el);if(!p?.keyframes?.length)return null;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce&&p.reducedMotion==='disable')return null;let a=animationStore.get(el);if(a&&restart)a.cancel();if(!a||restart){const opts={...(p.options||{})};if(opts.iterations==='Infinity')opts.iterations=Infinity;if(reduce&&p.reducedMotion==='shorten'){opts.duration=Math.min(Number(opts.duration)||500,80);opts.iterations=1;}a=el.animate(p.keyframes,opts);a.playbackRate=Number(p.playbackRate)||1;animationStore.set(el,a);}return a;}
function controlAnimation(el:HTMLElement|null,command:string,value=''){if(!el)return;const p=animationPayload(el);const css=p?.engine==='css'||el.dataset.uiAnimationEngine==='css';if(css){if(command==='play'){el.classList.remove('ui-animation-running');void el.offsetWidth;el.classList.add('ui-animation-running');el.style.animationPlayState='running';}else if(command==='pause')el.style.animationPlayState='paused';else if(command==='stop'){el.classList.remove('ui-animation-running');el.style.animation='';}else if(command==='reverse'){el.style.animationDirection=el.style.animationDirection==='reverse'?'normal':'reverse';el.classList.add('ui-animation-running');}return;}let a=animationStore.get(el);if(command==='play'){a=makeWaapi(el,true);a?.play();}else if(command==='pause'){a??=makeWaapi(el,false);a?.pause();}else if(command==='stop'){a?.cancel();animationStore.delete(el);}else if(command==='reverse'){a??=makeWaapi(el,false);a?.reverse();}else if(command==='seek'){a??=makeWaapi(el,false);if(a){a.pause();const d=Number(p?.options?.duration)||500;a.currentTime=Math.max(0,Math.min(100,Number(value)||0))/100*d;}}}
function setupAnimations(){document.querySelectorAll<HTMLElement>('[data-ui-animation-id]').forEach(el=>{const p=animationPayload(el);if(!p)return;const play=()=>controlAnimation(el,'play');if(p.trigger==='load')play();else if(p.trigger==='hover'){el.addEventListener('pointerenter',play);el.addEventListener('pointerleave',()=>controlAnimation(el,'stop'));}else if(p.trigger==='focus'){el.addEventListener('focusin',play);el.addEventListener('focusout',()=>controlAnimation(el,'stop'));}else if(p.trigger==='click')el.addEventListener('click',play);else if(p.trigger==='inView'){const io=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting))play()},{threshold:.15});io.observe(el);}else if(p.trigger==='scroll'&&p.engine==='waapi'){let raf=0;const update=()=>{raf=0;let a=animationStore.get(el);if(!a){a=makeWaapi(el,false);a?.pause();}if(!a)return;const r=el.getBoundingClientRect(),span=innerHeight+r.height,progress=Math.max(0,Math.min(1,(innerHeight-r.top)/span));a.currentTime=progress*(Number(p.options?.duration)||1000);};addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(update)},{passive:true});update();}});}
function run(a:UIAction,event:Event,source:HTMLElement){if(!conditionOk(a.condition||''))return;const t=target(a.target);const v=interpolate(a.value||'');switch(a.type){case'navigate':event.preventDefault();location.href=v||'/';break;case'show':if(t)t.hidden=false;break;case'hide':if(t)t.hidden=true;break;case'toggleClass':if(t)t.classList.toggle(v||'active');break;case'scrollTo':t?.scrollIntoView({behavior:'smooth',block:'start'});break;case'setState':{const i=v.indexOf('=');if(i>0){const k=v.slice(0,i).trim();let x:any=v.slice(i+1).trim();if(x==='true'||x==='false')x=x==='true';else if(!Number.isNaN(Number(x))&&x!=='')x=Number(x);state[k]=x;refreshBindings();}break;}case'toggleState':state[v]=!state[v];refreshBindings();break;case'setText':if(t)t.textContent=v;break;case'emit':source.dispatchEvent(new CustomEvent(v,{bubbles:true,detail:{state}}));break;case'submit':source.closest('form')?.requestSubmit();break;case'setComponentState':if(t)t.dataset.uiState=v||'default';break;case'playAnimation':case'startTimeline':controlAnimation(t,'play');break;case'pauseAnimation':controlAnimation(t,'pause');break;case'stopAnimation':case'stopTimeline':controlAnimation(t,'stop');break;case'reverseAnimation':controlAnimation(t,'reverse');break;case'seekAnimation':controlAnimation(t,'seek',v);break;}}
function dispatch(event:Event){const el=(event.target as HTMLElement|null)?.closest<HTMLElement>('[data-ui-actions]');if(!el)return;let actions:UIAction[]=[];try{actions=JSON.parse(el.dataset.uiActions||'[]')}catch{}for(const a of actions){const expected=a.event==='focus'?'focusin':a.event==='blur'?'focusout':a.event;if(expected===event.type)run(a,event,el);}}
for(const n of ['click','input','change','submit','reset','focusin','focusout','play','pause','ended'])document.addEventListener(n,dispatch);refreshBindings();setupAnimations();
